language: python
python:
  - "2.7"
  - "3.4"

sudo: false

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

# commands to run tests and style check
script:
  - flake8 .
  - nosetests --with-coverage --cover-erase --cover-branches --cover-package=scholastic

after_success:
  - coveralls

notifications:
  webhooks:
    - http://orchestrator.r53.us-west-1.cu.melt.sh/external/hooks/travis
